fury_test_qreal_not_eq_mixed – FURY
fury_test_qreal_not_eq_mixed Program
37 statements
Source File
Uses:
fury
FURY test of qreal.
Calls
Variables
force1 force2 force3 u_acceleration u_force u_length u_mass u_speed u_time test_passed
Source Code
fury_test_qreal_not_eq_mixed
Variables
Type Attributes Name Initial
type(qreal32) :: force1
A force.
type(qreal64) :: force2
A force.
type(qreal128) :: force3
A force.
type(uom64) :: u_acceleration
Acceleration unit.
type(uom64) :: u_force
Force unit.
type(uom64) :: u_length
Length unit.
type(uom64) :: u_mass
Mass unit.
type(uom64) :: u_speed
Speed unit.
type(uom64) :: u_time
Time unit.
logical :: test_passed(6)
List of passed tests.
Source Code
program fury_test_qreal_not_eq_mixed
!-----------------------------------------------------------------------------------------------------------------------------------
!< FURY test of [[qreal]].
!-----------------------------------------------------------------------------------------------------------------------------------
use fury
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
type(qreal32)  :: force1         !< A force.
type(qreal64)  :: force2         !< A force.
type(qreal128) :: force3         !< A force.
type(uom64)    :: u_acceleration !< Acceleration unit.
type(uom64)    :: u_force        !< Force unit.
type(uom64)    :: u_length       !< Length unit.
type(uom64)    :: u_mass         !< Mass unit.
type(uom64)    :: u_speed        !< Speed unit.
type(uom64)    :: u_time         !< Time unit.
logical        :: test_passed(6) !< List of passed tests.
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
test_passed = .false.
u_length = uom64(source='m [length]', name='metre')
u_mass = uom64(source='kg [mass]', name='kilogram')
u_time = uom64(source='s [time]', name='second')
u_speed = u_length / u_time
u_acceleration = u_speed / u_time
u_force = u_mass * u_acceleration
force1 = 1 * u_force
force2 = 2 * u_force
force3 = 3 * u_force
test_passed(1) = force1 /= force2
print "(A,L1)", '1 * force(float32) /= 2 * force(float64) => '//trim(str(test_passed(1)))//', is correct? ', test_passed(1)
test_passed(2) = force2 /= force1
print "(A,L1)", '2 * force(float64) /= 1 * force(float32) => '//trim(str(test_passed(2)))//', is correct? ', test_passed(2)
test_passed(3) = force1 /= force3
print "(A,L1)", '1 * force(float32) /= 3 * force(float128) => '//trim(str(test_passed(3)))//', is correct? ', test_passed(3)
test_passed(4) = force3 /= force1
print "(A,L1)", '3 * force(float128) /= 1 * force(float32) => '//trim(str(test_passed(4)))//', is correct? ', test_passed(4)
test_passed(5) = force2 /= force3
print "(A,L1)", '1 * force(float64) /= 3 * force(float128) => '//trim(str(test_passed(5)))//', is correct? ', test_passed(5)
test_passed(6) = force3 /= force2
print "(A,L1)", '3 * force(float128) /= 1 * force(float64) => '//trim(str(test_passed(6)))//', is correct? ', test_passed(6)
print "(A,L1)", new_line('a')//'Are all tests passed? ', all(test_passed)
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram fury_test_qreal_not_eq_mixed
All Programs
assignments basename_dir camelcase capitalize compact_real compact_real compact_real concatenation count_string csv_naive_parser decode encode equal escape extension fill free fury_test_bolt32 fury_test_bolt64 fury_test_qreal_add fury_test_qreal_add_aliases_failure fury_test_qreal_add_failure fury_test_qreal_add_mixed fury_test_qreal_add_mixed_failure fury_test_qreal_aliases fury_test_qreal_assign fury_test_qreal_conversions_complex fury_test_qreal_conversions_si fury_test_qreal_conversions_simple fury_test_qreal_div fury_test_qreal_div_mixed fury_test_qreal_eq fury_test_qreal_eq_mixed fury_test_qreal_mul fury_test_qreal_mul_mixed fury_test_qreal_not_eq fury_test_qreal_not_eq_mixed fury_test_qreal_pow fury_test_qreal_sub fury_test_qreal_sub_failure fury_test_qreal_sub_mixed fury_test_qreal_sub_mixed_failure fury_test_system_si fury_test_uom_add fury_test_uom_add_failure fury_test_uom_aliases fury_test_uom_assign fury_test_uom_assign_failure fury_test_uom_div fury_test_uom_mul fury_test_uom_parse_failure fury_test_uom_pow fury_test_uom_sub fury_test_uom_sub_failure greater_equal_than greater_than insert io_basic io_formatted is_digit is_integer is_number is_real join lower_equal_than lower_than not_equal partition read_file read_line read_lines replace reverse sadjustlr search sindex slen slice snakecase split srepeat sscan start_end startcase strim strip sverify swapcase test_all test_all test_all Test_Driver to_number unescape unique upper_lower write_file write_lines
Call graph
fury_test_qreal_not_eq_mixed calls uom64, str
str calls strf_i2p, str_a_r4p, str_a_i8p, str_r8p, str_i4p, strf_r4p, str_a_i1p, str_a_i4p, str_i2p, str_i1p, str_a_i2p, strf_i4p, str_i8p, str_bol, str_r4p, strf_r8p, str_a_r8p, strf_i8p, strf_i1p
str_a_r4p calls str_r4p
str_a_i8p calls str_i8p
str_r8p calls compact_real_string
str_a_i1p calls str_i1p
str_a_i4p calls str_i4p
str_a_i2p calls str_i2p
str_r4p calls compact_real_string
str_a_r8p calls str_r8p