compact_real – FURY
compact_real Program
16 statements
Source File
Uses:
penf
iso_fortran_env
PENF's testing program.
Calls
Variables
test_passed
Source Code
compact_real
Variables
Type Attributes Name Initial
logical :: test_passed(3)
List of passed tests.
Source Code
program compact_real
!-----------------------------------------------------------------------------------------------------------------------------------
!< PENF's testing program.
!-----------------------------------------------------------------------------------------------------------------------------------
use penf
use, intrinsic :: ISO_FORTRAN_ENV, only : stdout=>OUTPUT_UNIT
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
logical :: test_passed(3) !< List of passed tests.
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
call penf_init
test_passed = .false.
test_passed(1) = trim(str(n=1._R8P, compact=.true.))=='+0.1E+1'
print "(A,L1)", 'Compact 1.0: '//trim(str(n=1._R8P, compact=.true.))//', is correct? ', test_passed(1)
test_passed(2) = trim(str(n=1._R4P/3._R4P, compact=.true.))=='+0.333333E+0'
print "(A,L1)", 'Compact 1.0/3.0: '//trim(str(n=1._R4P/3._R4P, compact=.true.))//', is correct? ', test_passed(2)
test_passed(3) = trim(str(n=1._R16P/4._R16P, compact=.true.))=='+0.25E+0'
print "(A,L1)", 'Compact 1.0/4.0: '//trim(str(n=1._R16P/4._R16P, compact=.true.))//', is correct? ', test_passed(3)
write(stdout, "(A,L1)") new_line('a')//'Are all tests passed? ', all(test_passed)
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram compact_real
All Programs
assignments basename_dir camelcase capitalize compact_real compact_real compact_real concatenation count_string csv_naive_parser decode encode equal escape extension fill free fury_test_bolt32 fury_test_bolt64 fury_test_qreal_add fury_test_qreal_add_aliases_failure fury_test_qreal_add_failure fury_test_qreal_add_mixed fury_test_qreal_add_mixed_failure fury_test_qreal_aliases fury_test_qreal_assign fury_test_qreal_conversions_complex fury_test_qreal_conversions_si fury_test_qreal_conversions_simple fury_test_qreal_div fury_test_qreal_div_mixed fury_test_qreal_eq fury_test_qreal_eq_mixed fury_test_qreal_mul fury_test_qreal_mul_mixed fury_test_qreal_not_eq fury_test_qreal_not_eq_mixed fury_test_qreal_pow fury_test_qreal_sub fury_test_qreal_sub_failure fury_test_qreal_sub_mixed fury_test_qreal_sub_mixed_failure fury_test_system_si fury_test_uom_add fury_test_uom_add_failure fury_test_uom_aliases fury_test_uom_assign fury_test_uom_assign_failure fury_test_uom_div fury_test_uom_mul fury_test_uom_parse_failure fury_test_uom_pow fury_test_uom_sub fury_test_uom_sub_failure greater_equal_than greater_than insert io_basic io_formatted is_digit is_integer is_number is_real join lower_equal_than lower_than not_equal partition read_file read_line read_lines replace reverse sadjustlr search sindex slen slice snakecase split srepeat sscan start_end startcase strim strip sverify swapcase test_all test_all test_all Test_Driver to_number unescape unique upper_lower write_file write_lines
Call graph
compact_real calls str, penf_init
str calls strf_i8p, str_i1p, strf_r4p, strf_i4p, str_a_i8p, str_a_r4p, str_bol, str_a_i2p, strf_r8p, str_r8p, str_a_i4p, strf_i1p, str_i2p, str_i8p, str_r4p, strf_i2p, str_a_i1p, str_a_r8p, str_i4p
penf_init calls check_endian
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_r8p calls compact_real_string
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p