test_all – FURY
test_all Program
18 statements
Source File
Uses:
penf
iso_fortran_env
PENF's testing program.
Usage
 ./test_all
Calls
Source Code
test_all
Source Code
program test_all
!-----------------------------------------------------------------------------------------------------------------------------------
!< PENF's testing program.
!<
!<### Usage
!<```bash
!< ./test_all
!<```
!-----------------------------------------------------------------------------------------------------------------------------------
use penf
use, intrinsic :: ISO_FORTRAN_ENV, only : stdout=>OUTPUT_UNIT
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
call penf_init
call penf_print(unit=stdout)
print "(A)", ''
print "(A)", 'Testing IR_Precision tools'
print "(A)", 'Casting real-to-string: '//str(n=1._R8P)
print "(A)", 'Casting integer-to-string: '//str(n=11_I8P)
print "(A,"//FR8P//")", 'Casting string-to-real: ',cton(str='2.2d0', knd=1._R8P)
print "(A,"//FI4P//")", 'Casting integer-to-string: ',cton(str='43', knd=1_I4P)
print "(A)", 'Casting integer-to-string with zero padding: '//trim(strz(nz_pad=3, n=34_I8P))
#ifndef __GFORTRAN__
print "(A)", 'Casting real-to-bit_string: '//bstr(n=1._R4P)
#endif
print "(A)", 'Casting integer-to-bit_string: '//bstr(n=1_I4P)
#ifndef __GFORTRAN__
print "(A,"//FR4P//")", 'Casting bit_string-to-real: ', bcton(bstr='00111111100000000000000000000000', knd=1._R4P)
#endif
print "(A,"//FI4P//")", 'Casting bit_string-to-integer: ',bcton(bstr='00000000000000000000000000000001', knd=1_I4P)
print "(A)", 'Number of digit of 1023: '//str(n=digit(1023_I4P))
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram test_all
All Programs
assignments basename_dir camelcase capitalize compact_real compact_real compact_real concatenation count_string csv_naive_parser decode encode equal escape extension fill free fury_test_bolt32 fury_test_bolt64 fury_test_qreal_add fury_test_qreal_add_aliases_failure fury_test_qreal_add_failure fury_test_qreal_add_mixed fury_test_qreal_add_mixed_failure fury_test_qreal_aliases fury_test_qreal_assign fury_test_qreal_conversions_complex fury_test_qreal_conversions_si fury_test_qreal_conversions_simple fury_test_qreal_div fury_test_qreal_div_mixed fury_test_qreal_eq fury_test_qreal_eq_mixed fury_test_qreal_mul fury_test_qreal_mul_mixed fury_test_qreal_not_eq fury_test_qreal_not_eq_mixed fury_test_qreal_pow fury_test_qreal_sub fury_test_qreal_sub_failure fury_test_qreal_sub_mixed fury_test_qreal_sub_mixed_failure fury_test_system_si fury_test_uom_add fury_test_uom_add_failure fury_test_uom_aliases fury_test_uom_assign fury_test_uom_assign_failure fury_test_uom_div fury_test_uom_mul fury_test_uom_parse_failure fury_test_uom_pow fury_test_uom_sub fury_test_uom_sub_failure greater_equal_than greater_than insert io_basic io_formatted is_digit is_integer is_number is_real join lower_equal_than lower_than not_equal partition read_file read_line read_lines replace reverse sadjustlr search sindex slen slice snakecase split srepeat sscan start_end startcase strim strip sverify swapcase test_all test_all test_all Test_Driver to_number unescape unique upper_lower write_file write_lines
Call graph
test_all calls penf_print, str, cton, penf_init, strz, digit, bcton, bstr
str calls str_i4p, strf_i2p, str_a_r8p, strf_i1p, strf_r4p, str_a_r4p, str_a_i8p, str_r8p, strf_i4p, str_i1p, str_i2p, str_i8p, str_a_i4p, str_r4p, str_a_i2p, strf_r8p, strf_i8p, str_a_i1p, str_bol
cton calls ctoi_i2p, ctoi_i8p, ctoi_i1p, ctor_r4p, ctoi_i4p, ctor_r8p
penf_init calls check_endian
strz calls strz_i2p, strz_i1p, strz_i8p, strz_i4p
digit calls digit_i8, digit_i1, digit_i4, digit_i2
bcton calls bctoi_i1p, bctor_r4p, bctor_r8p, bctoi_i8p, bctoi_i4p, bctoi_i2p
bstr calls bstr_r4p, bstr_i2p, bstr_i8p, bstr_i4p, bstr_r8p, bstr_i1p
str_a_r8p calls str_r8p
str_a_r4p calls str_r4p
str_a_i8p calls str_i8p
str_r8p calls compact_real_string
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_i2p calls str_i2p
str_a_i1p calls str_i1p
bctoi_i1p calls str
bctor_r4p calls str
bctor_r8p calls str
bctoi_i8p calls str
bctoi_i4p calls str
bctoi_i2p calls str