Test_Driver – FURY
Test_Driver Program
7 statements
Source File
Uses:
befor64
Testing program for BeFoR64, Base64 encoding/decoding library for FoRtran poor men
Usage
 ./Test_Driver
Calls
Source Code
Test_Driver
Source Code
program Test_Driver
!-----------------------------------------------------------------------------------------------------------------------------------
!< Testing program for BeFoR64, Base64 encoding/decoding library for FoRtran poor men
!<
!<### Usage
!<```bash
!< ./Test_Driver
!<```
!-----------------------------------------------------------------------------------------------------------------------------------
use befor64, only : autotest ! Autotesting procedure.
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
print "(A)", 'Testing BeFoR64'
call autotest
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram Test_Driver
All Programs
assignments basename_dir camelcase capitalize compact_real compact_real compact_real concatenation count_string csv_naive_parser decode encode equal escape extension fill free fury_test_bolt32 fury_test_bolt64 fury_test_qreal_add fury_test_qreal_add_aliases_failure fury_test_qreal_add_failure fury_test_qreal_add_mixed fury_test_qreal_add_mixed_failure fury_test_qreal_aliases fury_test_qreal_assign fury_test_qreal_conversions_complex fury_test_qreal_conversions_si fury_test_qreal_conversions_simple fury_test_qreal_div fury_test_qreal_div_mixed fury_test_qreal_eq fury_test_qreal_eq_mixed fury_test_qreal_mul fury_test_qreal_mul_mixed fury_test_qreal_not_eq fury_test_qreal_not_eq_mixed fury_test_qreal_pow fury_test_qreal_sub fury_test_qreal_sub_failure fury_test_qreal_sub_mixed fury_test_qreal_sub_mixed_failure fury_test_system_si fury_test_uom_add fury_test_uom_add_failure fury_test_uom_aliases fury_test_uom_assign fury_test_uom_assign_failure fury_test_uom_div fury_test_uom_mul fury_test_uom_parse_failure fury_test_uom_pow fury_test_uom_sub fury_test_uom_sub_failure greater_equal_than greater_than insert io_basic io_formatted is_digit is_integer is_number is_real join lower_equal_than lower_than not_equal partition read_file read_line read_lines replace reverse sadjustlr search sindex slen slice snakecase split srepeat sscan start_end startcase strim strip sverify swapcase test_all test_all test_all Test_Driver to_number unescape unique upper_lower write_file write_lines
Call graph
test_driver calls autotest
autotest calls b64_encode, b64_decode, b64_init, str
b64_encode calls b64_encode_r8, b64_encode_i1_a, b64_encode_i4, b64_encode_r4_a, b64_encode_i1, b64_encode_i2, b64_encode_i2_a, b64_encode_string_a, b64_encode_r4, b64_encode_string, b64_encode_i8, b64_encode_r8_a, b64_encode_i8_a, b64_encode_i4_a
b64_decode calls b64_decode_r4_a, b64_decode_i1, b64_decode_string_a, b64_decode_i2, b64_decode_string, b64_decode_i8_a, b64_decode_r4, b64_decode_i2_a, b64_decode_i8, b64_decode_r8_a, b64_decode_i4, b64_decode_i1_a, b64_decode_i4_a, b64_decode_r8
str calls strf_i8p, str_i1p, strf_r4p, strf_i4p, str_a_i8p, str_a_r4p, str_bol, str_a_i2p, strf_r8p, str_r8p, str_a_i4p, strf_i1p, str_i2p, str_i8p, str_r4p, strf_i2p, str_a_i1p, str_a_r8p, str_i4p
b64_encode_r8 calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_i1 calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_string_a calls encode_bits, byte_size
b64_encode_r4 calls encode_bits
b64_encode_string calls encode_bits, byte_size
b64_encode_i8 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_i4_a calls encode_bits
byte_size calls byte_size_i8p, byte_size_i1p, byte_size_r4p, byte_size_chr, byte_size_r8p, byte_size_i2p, byte_size_i4p
b64_decode_r4_a calls decode_bits
b64_decode_i1 calls decode_bits
b64_decode_string_a calls byte_size, decode_bits
b64_decode_i2 calls decode_bits
b64_decode_string calls byte_size, decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_r4 calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_i8 calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i4 calls decode_bits
b64_decode_i1_a calls decode_bits
b64_decode_i4_a calls decode_bits
b64_decode_r8 calls decode_bits
str_a_i8p calls str_i8p
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_r8p calls compact_real_string
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p